// <auto-generated />
using System;
using HealingAssigns.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealingAssigns.Sql.Migrations
{
    [DbContext(typeof(HealingAssignsDb))]
    [Migration("20260710091341_AddPlayerClassTable")]
    partial class AddPlayerClassTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneePosition")
                        .HasColumnType("int");

                    b.Property<int>("AssigneeRoleListId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SymbolId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPosition")
                        .HasColumnType("int");

                    b.Property<int?>("TargetRoleListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeRoleListId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TargetRoleListId");

                    b.HasIndex("EncounterId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.PlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#C69B6D",
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FFFFFF",
                            Name = "Priest"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3FC7EB",
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FF7C0A",
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#AAD372",
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#FFF468",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#0070DD",
                            Name = "Shaman"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#F48CBA",
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#8788EE",
                            Name = "Warlock"
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RoleLists");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PlayerClassId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleListId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerClassId");

                    b.HasIndex("RoleListId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RoleSlots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Symbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Skull"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Star"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Circle"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Triangle"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Square"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Moon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cross"
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Assignment", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "AssigneeRoleList")
                        .WithMany()
                        .HasForeignKey("AssigneeRoleListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Entities.Encounter", "Encounter")
                        .WithMany("Assignments")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "TargetRoleList")
                        .WithMany()
                        .HasForeignKey("TargetRoleListId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssigneeRoleList");

                    b.Navigation("Encounter");

                    b.Navigation("Symbol");

                    b.Navigation("TargetRoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.Session", "Session")
                        .WithMany("Encounters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.Session", "Session")
                        .WithMany("RoleLists")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleSlot", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.PlayerClass", "PlayerClass")
                        .WithMany()
                        .HasForeignKey("PlayerClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "RoleList")
                        .WithMany("Slots")
                        .HasForeignKey("RoleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerClass");

                    b.Navigation("RoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Session", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("RoleLists");
                });
#pragma warning restore 612, 618
        }
    }
}
