// <auto-generated />
using System;
using HealingAssigns.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealingAssigns.Sql.Migrations
{
    [DbContext(typeof(HealingAssignsDb))]
    [Migration("20260712053026_AddRoleSpecPlayerTables")]
    partial class AddRoleSpecPlayerTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneePosition")
                        .HasColumnType("int");

                    b.Property<int>("AssigneeRoleListId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<int?>("SymbolId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetPosition")
                        .HasColumnType("int");

                    b.Property<int?>("TargetRoleListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeRoleListId");

                    b.HasIndex("SymbolId");

                    b.HasIndex("TargetRoleListId");

                    b.HasIndex("EncounterId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("SpecId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SpecId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.PlayerClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlayerClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#C69B6D",
                            Icon = "⚔️",
                            Name = "Warrior"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#FFFFFF",
                            Icon = "🙏",
                            Name = "Priest"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#3FC7EB",
                            Icon = "🔮",
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#FF7C0A",
                            Icon = "🌿",
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#AAD372",
                            Icon = "🏹",
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#FFF468",
                            Icon = "🗡️",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#0070DD",
                            Icon = "⚡",
                            Name = "Shaman"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#F48CBA",
                            Icon = "⚜️",
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#8788EE",
                            Icon = "😈",
                            Name = "Warlock"
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Healer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tank"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dps"
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RoleLists");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("PlayerClassId")
                        .HasColumnType("int");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleListId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerClassId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RoleListId", "SortOrder")
                        .IsUnique();

                    b.ToTable("RoleSlots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Spec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerClassId")
                        .HasColumnType("int");

                    b.Property<string>("RaidHelperKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerClassId");

                    b.HasIndex("RaidHelperKey")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Specs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arms",
                            PlayerClassId = 1,
                            RaidHelperKey = "Arms",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fury",
                            PlayerClassId = 1,
                            RaidHelperKey = "Fury",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            Name = "Protection",
                            PlayerClassId = 1,
                            RaidHelperKey = "Protection",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Discipline",
                            PlayerClassId = 2,
                            RaidHelperKey = "Discipline",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Holy",
                            PlayerClassId = 2,
                            RaidHelperKey = "Holy",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Shadow",
                            PlayerClassId = 2,
                            RaidHelperKey = "Shadow",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            Name = "Arcane",
                            PlayerClassId = 3,
                            RaidHelperKey = "Arcane",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            Name = "Fire",
                            PlayerClassId = 3,
                            RaidHelperKey = "Fire",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            Name = "Frost",
                            PlayerClassId = 3,
                            RaidHelperKey = "Frost",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Balance",
                            PlayerClassId = 4,
                            RaidHelperKey = "Balance",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "Feral",
                            PlayerClassId = 4,
                            RaidHelperKey = "Feral",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            Name = "Guardian",
                            PlayerClassId = 4,
                            RaidHelperKey = "Guardian",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "Restoration",
                            PlayerClassId = 4,
                            RaidHelperKey = "Restoration",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "Dreamstate",
                            PlayerClassId = 4,
                            RaidHelperKey = "Dreamstate",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 15,
                            Name = "Beast Mastery",
                            PlayerClassId = 5,
                            RaidHelperKey = "Beastmastery",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Marksmanship",
                            PlayerClassId = 5,
                            RaidHelperKey = "Marksmanship",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Survival",
                            PlayerClassId = 5,
                            RaidHelperKey = "Survival",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Assassination",
                            PlayerClassId = 6,
                            RaidHelperKey = "Assassination",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "Combat",
                            PlayerClassId = 6,
                            RaidHelperKey = "Combat",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "Subtlety",
                            PlayerClassId = 6,
                            RaidHelperKey = "Subtlety",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "Elemental",
                            PlayerClassId = 7,
                            RaidHelperKey = "Elemental",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Enhancement",
                            PlayerClassId = 7,
                            RaidHelperKey = "Enhancement",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "Restoration",
                            PlayerClassId = 7,
                            RaidHelperKey = "Restoration1",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 24,
                            Name = "Holy",
                            PlayerClassId = 8,
                            RaidHelperKey = "Holy1",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 25,
                            Name = "Protection",
                            PlayerClassId = 8,
                            RaidHelperKey = "Protection1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            Name = "Retribution",
                            PlayerClassId = 8,
                            RaidHelperKey = "Retribution",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Affliction",
                            PlayerClassId = 9,
                            RaidHelperKey = "Affliction",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Demonology",
                            PlayerClassId = 9,
                            RaidHelperKey = "Demonology",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            Name = "Destruction",
                            PlayerClassId = 9,
                            RaidHelperKey = "Destruction",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Symbol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Symbols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "💀",
                            Name = "Skull"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "⭐",
                            Name = "Star"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "🟠",
                            Name = "Circle"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "🔶",
                            Name = "Diamond"
                        },
                        new
                        {
                            Id = 5,
                            Icon = "🔺",
                            Name = "Triangle"
                        },
                        new
                        {
                            Id = 6,
                            Icon = "🟦",
                            Name = "Square"
                        },
                        new
                        {
                            Id = 7,
                            Icon = "🌙",
                            Name = "Moon"
                        },
                        new
                        {
                            Id = 8,
                            Icon = "❌",
                            Name = "Cross"
                        });
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Assignment", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "AssigneeRoleList")
                        .WithMany()
                        .HasForeignKey("AssigneeRoleListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Entities.Encounter", "Encounter")
                        .WithMany("Assignments")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Entities.Symbol", "Symbol")
                        .WithMany()
                        .HasForeignKey("SymbolId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "TargetRoleList")
                        .WithMany()
                        .HasForeignKey("TargetRoleListId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssigneeRoleList");

                    b.Navigation("Encounter");

                    b.Navigation("Symbol");

                    b.Navigation("TargetRoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.Session", "Session")
                        .WithMany("Encounters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Player", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.Spec", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Spec");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.Session", "Session")
                        .WithMany("RoleLists")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleSlot", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.PlayerClass", "PlayerClass")
                        .WithMany()
                        .HasForeignKey("PlayerClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealingAssigns.Sql.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HealingAssigns.Sql.Entities.RoleList", "RoleList")
                        .WithMany("Slots")
                        .HasForeignKey("RoleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("PlayerClass");

                    b.Navigation("RoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Spec", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Entities.PlayerClass", "PlayerClass")
                        .WithMany()
                        .HasForeignKey("PlayerClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlayerClass");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Encounter", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.RoleList", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Entities.Session", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("RoleLists");
                });
#pragma warning restore 612, 618
        }
    }
}
