// <auto-generated />
using System;
using HealingAssigns.Sql;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HealingAssigns.Sql.Migrations
{
    [DbContext(typeof(HealingAssignsDb))]
    partial class HealingAssignsDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HealingAssigns.Sql.Assignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssigneePosition")
                        .HasColumnType("int");

                    b.Property<int>("AssigneeRoleListId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EncounterId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TargetPosition")
                        .HasColumnType("int");

                    b.Property<int?>("TargetRoleListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeRoleListId");

                    b.HasIndex("EncounterId");

                    b.HasIndex("TargetRoleListId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Encounter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("Encounters");
                });

            modelBuilder.Entity("HealingAssigns.Sql.RoleList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.ToTable("RoleLists");
                });

            modelBuilder.Entity("HealingAssigns.Sql.RoleSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleListId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleListId");

                    b.ToTable("RoleSlots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Assignment", b =>
                {
                    b.HasOne("HealingAssigns.Sql.RoleList", "AssigneeRoleList")
                        .WithMany()
                        .HasForeignKey("AssigneeRoleListId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.Encounter", "Encounter")
                        .WithMany("Assignments")
                        .HasForeignKey("EncounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HealingAssigns.Sql.RoleList", "TargetRoleList")
                        .WithMany()
                        .HasForeignKey("TargetRoleListId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AssigneeRoleList");

                    b.Navigation("Encounter");

                    b.Navigation("TargetRoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Encounter", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Session", "Session")
                        .WithMany("Encounters")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.RoleList", b =>
                {
                    b.HasOne("HealingAssigns.Sql.Session", "Session")
                        .WithMany("RoleLists")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("HealingAssigns.Sql.RoleSlot", b =>
                {
                    b.HasOne("HealingAssigns.Sql.RoleList", "RoleList")
                        .WithMany("Slots")
                        .HasForeignKey("RoleListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RoleList");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Encounter", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("HealingAssigns.Sql.RoleList", b =>
                {
                    b.Navigation("Slots");
                });

            modelBuilder.Entity("HealingAssigns.Sql.Session", b =>
                {
                    b.Navigation("Encounters");

                    b.Navigation("RoleLists");
                });
#pragma warning restore 612, 618
        }
    }
}
